"""add kind column to money_flows

Revision ID: 263dc2b5892e
Revises: 2493b19c62a2
Create Date: 2025-09-02 10:00:40.704583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '263dc2b5892e'
down_revision: Union[str, None] = '2493b19c62a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('money_flows', sa.Column('kind', sa.Enum('EXPENSE', 'INCOME', name='money_flow_kind'), server_default='expense', nullable=False))
    op.alter_column('money_flows', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('money_flows', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_money_flows_kind'), 'money_flows', ['kind'], unique=False)
    op.create_index('ix_money_flows_occurred_kind', 'money_flows', ['occurred_date', 'kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_money_flows_occurred_kind', table_name='money_flows')
    op.drop_index(op.f('ix_money_flows_kind'), table_name='money_flows')
    op.alter_column('money_flows', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('money_flows', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('money_flows', 'kind')
    # ### end Alembic commands ###
